# Generated by Django 6.0.4 on 2026-05-14 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0068_add_bookmark_url_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='latest_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest_article', to='bookmarks.bookmarkasset'),
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selector', models.JSONField()),
                ('selected_text', models.TextField()),
                ('color', models.CharField(choices=[('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue'), ('pink', 'Pink'), ('primary', 'Theme')], default='yellow', max_length=16)),
                ('note_content', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('article_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='bookmarks.bookmarkasset')),
                ('bookmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='bookmarks.bookmark')),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
    ]
