# Generated by Django 6.0.4 on 2026-05-26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0069_bookmark_latest_article_annotation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="article_asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="annotations",
                to="bookmarks.bookmarkasset",
            ),
        ),
    ]
