# Generated by Django 6.0.4 on 2026-05-28 15:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0070_preserve_annotations_when_article_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_position_start', models.IntegerField(blank=True, null=True)),
                ('text_quote_exact', models.CharField(blank=True, default='', max_length=1024)),
                ('text_quote_prefix', models.CharField(blank=True, default='', max_length=512)),
                ('text_quote_suffix', models.CharField(blank=True, default='', max_length=512)),
                ('element_selector', models.JSONField(blank=True, null=True)),
                ('progress', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('scroll_top', models.IntegerField(default=0)),
                ('scroll_height', models.IntegerField(default=0)),
                ('client_width', models.IntegerField(default=0)),
                ('client_height', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('article_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookmarks.bookmarkasset')),
                ('bookmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to='bookmarks.bookmark')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'bookmark'), name='unique_reading_progress_per_user_bookmark')],
            },
        ),
    ]
