# Generated by Django 5.2.3 on 2026-06-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0073_userprofile_bookmark_actions_statuses"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="reader_settings",
            field=models.JSONField(default=dict),
        ),
    ]
