# Generated by Django 5.2.3 on 2026-06-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0074_add_reader_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bookmark_quick_edits",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bookmark_status_display_mode",
            field=models.CharField(
                choices=[("text", "Text"), ("icon", "Icon")],
                default="icon",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bookmark_quick_edit_display_mode",
            field=models.CharField(
                choices=[("text", "Text"), ("icon", "Icon")],
                default="icon",
                max_length=10,
            ),
        ),
    ]
