# Generated by Django 5.2.3 on 2026-06-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0075_add_bookmark_quick_edits"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="highlights_search_preferences",
            field=models.JSONField(default=dict),
        ),
    ]
