# Generated by Django 5.2.3 on 2026-06-16 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0076_add_highlights_search_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="highlights_per_page",
            field=models.IntegerField(
                default=50, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
