# Generated by Django 5.2.3 on 2026-06-23 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0081_add_highlights_sidebar_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="highlight_copy_default_action",
            field=models.CharField(
                choices=[
                    ("both", "Copy all"),
                    ("highlight", "Copy highlight only"),
                    ("note", "Copy annotation only"),
                ],
                default="both",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="highlight_copy_format",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
