# Generated by Django 5.2.3 on 2026-06-29 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0082_add_highlight_copy_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="enable_random_button",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="random_mode",
            field=models.CharField(
                choices=[("list", "List"), ("single", "Single")],
                default="list",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="random_target",
            field=models.CharField(
                choices=[
                    ("url", "URL"),
                    ("reader", "Reader"),
                    ("snapshot", "Snapshot"),
                    ("details", "Details"),
                ],
                default="url",
                max_length=10,
            ),
        ),
    ]
