# Generated by Django 5.2.3 on 2026-06-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0083_userprofile_enable_random_button_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmarkasset",
            name="next_retry_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bookmarkasset",
            name="retry_count",
            field=models.IntegerField(default=0),
        ),
    ]
