# Generated by Django 6.0.4 on 2026-06-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0084_add_snapshot_retry_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='enable_preview_image_placeholders',
            field=models.BooleanField(default=True),
        ),
    ]
