# Generated by Django 6.0.4 on 2026-06-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0085_userprofile_enable_preview_image_placeholders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
