# Generated by Django 6.0.4 on 2026-07-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0086_bookmark_title_to_textfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaviconCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=512, unique=True)),
                ('favicon_file', models.CharField(blank=True, default='', max_length=512)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('missing', 'Missing')], default='pending', max_length=20)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'next_retry_at'], name='bookmarks_f_status_6ff91f_idx')],
            },
        ),
    ]
