# Generated by Django 6.0.4 on 2026-07-01 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0088_populate_faviconcache'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='favicon_file',
        ),
    ]
