# Generated by Django 6.0.4 on 2026-07-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0089_remove_bookmark_favicon_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='highlights_tag_grouping',
            field=models.CharField(choices=[('alphabetical', 'Alphabetical'), ('smart_tree', 'Smart tree'), ('disabled', 'Disabled')], default='alphabetical', max_length=12),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tag_grouping',
            field=models.CharField(choices=[('alphabetical', 'Alphabetical'), ('smart_tree', 'Smart tree'), ('disabled', 'Disabled')], default='alphabetical', max_length=12),
        ),
    ]
