# Generated by Django 5.2.4 on 2026-07-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0090_alter_userprofile_highlights_tag_grouping_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bookmark_toolbar_auto_hide",
            field=models.BooleanField(default=False),
        ),
    ]
