# Generated by Django 6.0.4 on 2026-08-18 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0090_rsssubscription'),
        ('bookmarks', '0092_clear_favicons'),
    ]

    operations = [
    ]
