# Generated by Django 6.0.4 on 2026-08-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks", "0092_clear_favicons"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="preview_image_next_retry_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="preview_image_retry_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
