# Generated by Django 6.0.4 on 2026-08-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0093_add_preview_image_retry_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarkasset',
            name='scheduling_priority',
            field=models.IntegerField(default=0),
        ),
    ]
